// styles/home.styles.js
import { StyleSheet } from "react-native";
import { COLORS } from "@constants/colors";

export const styles = StyleSheet.create({
  addButton: {
    alignItems: "center",
    backgroundColor: COLORS.primary,
    borderRadius: 24,
    elevation: 3,
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingVertical: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  addButtonText: {
    color: COLORS.white,
    fontWeight: "600",
    marginLeft: 4,
  },
  balanceAmount: {
    color: COLORS.text,
    fontSize: 32,
    fontWeight: "bold",
    marginBottom: 20,
  },
  balanceCard: {
    backgroundColor: COLORS.card,
    borderRadius: 20,
    elevation: 3,
    marginBottom: 20,
    padding: 20,
    shadowColor: COLORS.shadow,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  balanceStatAmount: {
    fontSize: 18,
    fontWeight: "600",
  },
  balanceStatItem: {
    alignItems: "center",
    flex: 1,
  },
  balanceStatLabel: {
    color: COLORS.textLight,
    fontSize: 14,
    marginBottom: 4,
  },
  balanceStats: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  balanceTitle: {
    color: COLORS.textLight,
    fontSize: 16,
    marginBottom: 8,
  },
  categoryIconContainer: {
    alignItems: "center",
    backgroundColor: "#F5F5F5",
    borderRadius: 20,
    height: 40,
    justifyContent: "center",
    marginRight: 12,
    width: 40,
  },
  container: {
    backgroundColor: COLORS.background,
    flex: 1,
  },
  content: {
    padding: 20,
    paddingBottom: 0,
  },
  deleteButton: {
    borderLeftColor: COLORS.border,
    borderLeftWidth: 1,
    padding: 15,
  },
  emptyState: {
    alignItems: "center",
    backgroundColor: COLORS.card,
    borderRadius: 16,
    elevation: 2,
    justifyContent: "center",
    marginTop: 10,
    padding: 30,
    shadowColor: COLORS.shadow,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  emptyStateButton: {
    alignItems: "center",
    backgroundColor: COLORS.primary,
    borderRadius: 20,
    elevation: 2,
    flexDirection: "row",
    paddingHorizontal: 16,
    paddingVertical: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
  },
  emptyStateButtonText: {
    color: COLORS.white,
    fontWeight: "600",
    marginLeft: 6,
  },
  emptyStateIcon: {
    marginBottom: 16,
  },
  emptyStateText: {
    color: COLORS.textLight,
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 20,
    textAlign: "center",
  },
  emptyStateTitle: {
    color: COLORS.text,
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 8,
  },
  header: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
    paddingHorizontal: 0,
    paddingVertical: 12,
  },
  headerLeft: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
  },
  headerLogo: {
    height: 75,
    width: 75,
  },
  headerRight: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
  },
  headerTitle: {
    color: COLORS.text,
    fontSize: 28,
    fontWeight: "bold",
  },
  loadingContainer: {
    alignItems: "center",
    backgroundColor: COLORS.background,
    flex: 1,
    justifyContent: "center",
  },
  logoutButton: {
    backgroundColor: COLORS.card,
    borderRadius: 20,
    elevation: 1,
    padding: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  sectionTitle: {
    color: COLORS.text,
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 15,
  },
  statDivider: {
    borderColor: COLORS.border,
    borderRightWidth: 1,
  },
  transactionAmount: {
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 4,
  },
  transactionCard: {
    alignItems: "center",
    backgroundColor: COLORS.card,
    borderRadius: 12,
    elevation: 2,
    flexDirection: "row",
    marginBottom: 10,
    shadowColor: COLORS.shadow,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  transactionCategory: {
    color: COLORS.textLight,
    fontSize: 14,
  },
  transactionContent: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    padding: 15,
  },
  transactionDate: {
    color: COLORS.textLight,
    fontSize: 12,
  },
  transactionLeft: {
    flex: 1,
  },
  transactionRight: {
    alignItems: "flex-end",
  },
  transactionTitle: {
    color: COLORS.text,
    fontSize: 16,
    fontWeight: "500",
    marginBottom: 4,
  },
  transactionsContainer: {
    marginBottom: 20,
  },
  transactionsHeaderContainer: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
    paddingBottom: 5,
  },
  transactionsList: {
    flex: 1,
    marginHorizontal: 20,
  },
  transactionsListContent: {
    paddingBottom: 20,
  },
  usernameText: {
    color: COLORS.text,
    fontSize: 16,
    fontWeight: "600",
  },
  welcomeContainer: {
    flex: 1,
  },
  welcomeText: {
    color: COLORS.textLight,
    fontSize: 14,
    marginBottom: 2,
  },
});